### ISSUE TITLE
Proposal: Microcomputer

### ISSUE THREAD

**Issue by DRMacIver** [computeranonymous/computer#123] opened 2013-10-04 08:28 UTC
So as per my comment in #121  last night was super crowded. This is a problem because a) A lot of people find crowds very intimidating and b) As a new person, joining a crowd of people you don't know can be terrifying. Most people didn't know each other last night (which was awesome. One of my feared failure modes was that it would just be some specific in-group), but this will rapidly become a problem.

So it would be nice to have a way to gather small groups together as an alternative computer thing. Naturally we should call this "microcomputer".

Because it's me writing this, I of course think we should solve this problem with a randomized algorithm! 

Sketch proposal:

We pick a week for microcomputer that we are not otherwise doing computer. Everyone who is interested signs themselves up by contacting someone central privately (I am happy to be that someone). Signups can occur in groups of 1-3 people (some people will be uncomfortable going to these things on their own and will want a buddy to back them up).

We randomly combine these signups into groups of 4-8 people (I don't know what the optimal algorithm here is - it should probably be designed to minimize the total number of groups). They then arrange amongst themselves a day of the week and a venue to meet up. Computer rules apply for that meet-up, but it's much smaller than the main computer groups.

**Comment by drtortoise** [comment] 2013-10-04 09:51
"contacting someone central privately" o_0

**Comment by DRMacIver** [comment] 2013-10-04 09:53
Because issue #113. Happy for other coordination strategies to be suggested.

**Comment by adacable** [comment] 2013-10-04 10:02
@DRMacIver [we're talking about the bin packing problem](https://en.wikipedia.org/wiki/First_fit_algorithm).

:+1: on the name. Proposal that any meetup of 2-3 people who computer is to be known as a "arduino" and anything 4-6 is a raspbery pi. 

Could we do this completely in code? I think the centralisation is kinda a must(distributed systems are /hard/) but code would keep any human biases out.

You should also be able to request people not to be in meetups with.

**Comment by tef** [comment] 2013-10-04 10:15
This sounds like speed dating.

**Comment by drtortoise** [comment] 2013-10-04 10:25
@DRMacIver I was more surprised that there seems to be a central organisation of people. Are you co-ordinating microcomputers for the whole world or just east london?

also +1 for this sounds like speed dating, maybe I'll just go to the pub with friends instead :/

**Comment by DRMacIver** [comment] 2013-10-04 11:01
@drcable  Yes. This can and should be done in code with an open source program. Ideally seeded in a verifiable manner.
@drtortoise Probably just london. If there's an open source program for arranging it it's easy for other people to do.

I don't think it's much like speed dating at all. It's an opportunity to meet in groups of N > 2 but < uncomfortably large.

And, well, if you're comfortable with large groups and don't want to do this that's fine? It may be solving a problem you don't have, I just wanted to see if this was a problem that people felt needed solving given the large group.

**Comment by drtortoise** [comment] 2013-10-04 11:05
I'm one of those people who dont like large groups,  but pogramming a thing, where you can select your 1-3 favourite people, and also put people you dont want to be matched with, and availability times, and it tells you to go to a a certain place at a certain time just seems... eh... worse.

**Comment by ntlk** [comment] 2013-10-04 11:07
Do we have to solve this with technology? Could we all just not try to make more effort to get to know people we don't know yet and help newcomers make friends?

On 4 October 2013 at 12:06:13, L. Sandvik (notifications@github.com) wrote:

I'm one of those people who dont like large groups, but pogramming a thing, where you can select your 1-3 favourite people, and also put people you dont want to be matched with, and availability times, and it tells you to go to a a certain place at a certain time just seems... eh... worse.

**Comment by drtortoise** [comment] 2013-10-04 11:08
maybe I don't like it because it seems like "computer, but making sure people I don't like that much shows up"

**Comment by adacable** [comment] 2013-10-04 11:09
The problems isn't people who come to computer not making friends. The problem is people who can't come to computer because of noise and crowds and people.

**Comment by ntlk** [comment] 2013-10-04 11:10
Wouldn't that be solved by having more meetings, hence fewer occasions when large groups would turn up? 

On 4 October 2013 at 12:09:33, Thomas Walpole (notifications@github.com) wrote:

The problems isn't people who come to computer not making friends. The problem is people who can't come to computer because of noise and crowds and people.

**Comment by tef** [comment] 2013-10-04 12:26
We're likely to have a smaller amount of people at the next one. If it is as big, we'll have the meetings more regularly, or move venue.

Either way I'm strongly against more algorithms and code for what is 'Turn up to the pub'

**Comment by tef** [comment] 2013-10-04 23:56
I'm closing this. If you want to do this, please go ahead, but I won't consider it canon.

**Closed as completed by tef** 2013-10-04 23:56 UTC
Labels: proposal
